### PR TITLE
Adding in information on creating new template versions/releases

### PR DESCRIPTION
**Pull request by conbainbridge**
Edits to, added a section called "Creating new versions of templates": docs-gitbook/developers/getting-started-on-development.md

(Please ignore the edits to the other developers file, this was a merging issue that I can confirm is ok later - both should be identical but Github seems confused...)

### CODE REVIEW

**Comment by jkhartshorne** [comment]
I don't know. I feel like "Understanding the Front End" and "Understanding Docker" are still useful. I feel like for people who want to customize a Pushkin site beyond what we document or who want to contribute, there are a lot of technologies to learn about, and it's helpful to have guidance on where to start. In fact, if anything, I'd like to extend these sections to include more resources that you have found useful. 

But this text might be in the wrong place now and could be moved elsewhere.

**Comment by conbainbridge** [comment]
@jkhartshorne This is a Github snafu from having an identical edit to both repos that it failed to understand was identical, the file still has those sections: https://github.com/conbainbridge/pushkin/blob/master/docs-gitbook/developers/getting-started-on-development.md

**Comment by jkhartshorne** [comment]
@conbainbridge I'm confused. Is this pull request still needed? Or should it be closed without merging?

**Comment by conbainbridge** [comment]
@jkhartshorne I think you had asked me to submit as a pull request, so you would update the text (under ## Creating new versions of templates) before merging in?

**Comment by jkhartshorne** [comment]
Replacing this with the following pull request: https://github.com/pushkin-consortium/pushkin/pull/59

**Pull request closed without merging**
